services:
    db:
        image: mysql:8.0
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: db
            MYSQL_USER: user
            MYSQL_PASSWORD: password
        volumes:
            - ./.volumes/db:/var/lib/mysql

    wp:
        image: wordpress:latest
        environment:
            WORDPRESS_DB_HOST: db:3306
            WORDPRESS_DB_USER: user
            WORDPRESS_DB_PASSWORD: password
            WORDPRESS_DB_NAME: db
        volumes:
            - ./.volumes/wp:/var/www/html
        depends_on:
            - db

    nginx:
        image: nginx:latest
        ports:
            - 80:80
            - 443:443
        volumes:
          - ./nginx-conf:/etc/nginx/conf.d
          - ./.volumes/wp:/var/www/html
          - ./.volumes/nginx-certbot:/etc/letsencrypt
        depends_on:
            - wp

    certbot:
        image: certbot/certbot
        volumes:
          - ./.volumes/nginx-certbot:/etc/letsencrypt
        ommand: certonly --webroot --webroot-path=/var/www/html --email sammy@your_domain --agree-tos --no-eff-email --staging -d your_domain -d www.your_domain
